package com.jie;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.jie.model.User;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	/**
	 * @description 设置表和主键以及model的映射
	 * @auth weishujie
	 * @creattime 2017年8月1日下午7:52:50
	 * @param arp
	 */
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("user", "id", User.class);
	}
}
